# Generated by Django 5.0 on 2023-12-29 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taskapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Subordinate',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taskapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='taskapp.lead')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='taskapp.subordinate')),
            ],
        ),
        migrations.AddField(
            model_name='subordinate',
            name='assigned_tasks',
            field=models.ManyToManyField(blank=True, related_name='assigned_subordinates', to='taskapp.task'),
        ),
        migrations.AddField(
            model_name='subordinate',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, related_name='completed_subordinates', to='taskapp.task'),
        ),
        migrations.AddField(
            model_name='subordinate',
            name='unassigned_tasks',
            field=models.ManyToManyField(blank=True, related_name='unassigned_subordinates', to='taskapp.task'),
        ),
    ]
