# Generated by Django 5.0 on 2023-12-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Subordinate', 'Subordinate')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
